language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  app: secret-coast-74205
  api_key:
    secure: O3ceug1xkYAt2VBdjgDjjDPkZbzHdmbDqVl5jDbsDksfn82IGapKkOBlxZs7ka+s8xEkBKZjzwvjIWCbjubBUtCFUY91/deAslT3F2rBQ1PtCCnxckcvXZ+wSz/iCey+8581+POQgvJmwYiJFatpC1ONKRx7vojxva6L90znvcoAYXcT+GnmZfshC9rHHz+nj0AxYKco/TgemnhIW2kjgsizwbW+WcdNO8ma2hmLPCyFM3NCe78yHsbf/9IMx+QP52z7ItFpQUG1xrxlfnAfh1HcHNvkS6iSSTmG9/hzUocpyqocVzlT7m0qnT3hzTlQUvACMA5Jff20ul6J7HGKBpXZrI+xK4z0o1dIUJP4tJyX809cgEP4atKwvIRvzNv3c+5nPzSSn2q9cfpqoUrz1QrVjCyRywVllFAaV14cedb8LWKAP8BSg0D/YdkcxW5vZ2TdALD3GQirBa64cEO6/mjaUSRB24gVrRwPzA6awyEH/+fD6Q1y3YPbCal4Xmy7oehlTez/cKBKaoWPke2H7rYxLtG2KOOkVcMY0uOuLF13tG7pGoJrVC+xJOA+4FBf6rjg3epv8Qbl+st0449sYIpkZWB3w7cyv7eF65MdImIBjQX3pTNEYS8pYaBYrvxt++5xEVk7wbo76NYCsR6gtmF9iTjOPANmdDDrBneaYrY=
