language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  app: cryptic-plateau-81627
  api_key:
    secure: XN6HygMkSM8YIUfExyNAOyqqywrDGezj+ugi0zRH6/Tig4aerHCuyau7ZEt0i4OygPvpPAg+O8NO9sdpr8vj+qdUMsa6PbrFXwCj5AC3++JgIZFoFj3GLVajuD7HnsVm+UdLQOGO4bL2ULmG8hbgykx9JHuaKttqdtvkgKJfIuQTr8j8QhRwi/FqYTs6E7jqpjLcxLiSpYBrBjP1uM6d691eKxwjLlW8OyszMf19yMUOn2JggKHyhV0cBPU34hEbdrV3eav6phNC4aWiPw/qMV7dxm8I80bprZIeSmzLrwKNP8f3sJ0H3K+yO0C4BjhJZnRPH2cXWclS0zTf2gggVx59PspLP5xBWGZA0qnzN+MLUArj5JjZlCHFRu7AcZUW0UljBxNZ41talAJbnI6l9/wqyuOTuxmVq6iSEgbNn4iQ3dnZ8+LZZiCP3X7+gzPT33jrgsF3icY1H2QPTiyty6sBEUxlUuttMfDiV936BaZvMEHKUis0S592H9vHCYLMPL0z2HFv8Hn8WhvkAxan6vfE+dGiXE9z8iUpKrOHbvShncars1i2/HFgzVKr1dmAUTEddMXZNgCpGfLzT/6yiWbsVX753qiJePqBZoF2rZMaGtdOEwQR5e+I9ftNQujGHC3jTxTguZF9yrZICwKN49J3UtEqKuGbIAQyN+MZOlE=
