language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  app: secret-coast-74205
  api_key:
    secure: J82r5b/PflK0+RI5mWYJAGH/k2Hg+0HEnL1SMLRuI6nBAYzeYrawHs+xYUIPqtPUT0S6n4lHeaODH49kKs+CvVHWf4eX9ZplUm0uIFL8k4OEGdfeU8y/i6V8M7WmO1+vMPds/67UhAvE5KtXkA6ZtG1ml4xWBmdv/itvitQwP8y7dVhiJ90IQx6QtEQ78oVTLXbiF1XFaB7oVsEwfsv4BpEYWD3dqugIIkKMBVChRwaFceGrsh8b05nsZc59fX/ROz8Gc1z69ZrMJTaqXICTMjAC+3TEohjAv9tBY7QZIejHgczDmMfd/Mxc3D9/jNSfBfMnrOZ0dN/VqOpZccZ5d1C5FbzBy3GLlMqx4LknOK0Ujjr7JyfhgCDh8XXW14IFUbLkKIrjzNp/ZfzNyut0LgEaffmSjY0fqn9NLn2DIi0q/q6VMLYtWvWk/f76f+/LtY3w/d3patJki0F+SpZaTDBZEjUWlaZ6q/DyAFLdWP4GP2sMnnRAhRJLShyOhuaEiLBtjP2mf8K1yH5kcAikQAZEMIPOPugv/BnwO8rrhRUQTmd9wpf90b2ubLIX4J+pZsgqropuoaZDnTji16zbUb6OiPrvFGwVUzlsMU8FXYphMczFbY+dJxpfps6V/feEtdii4WHycUrjsKPeVyQkkx3Javvls8Tm+zSiynEOqLw=
